version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=YOUR_MONGODB_CONNECTION_STRING

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend